from cats.domain.exceptions.base import ApplicationError


class CatAlreadyExistError(ApplicationError):
    pass
